# Generated by Django 6.0 on 2025-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PortfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github", models.URLField()),
                ("linkedin", models.URLField()),
                ("instagram", models.URLField()),
            ],
        ),
    ]
